server:
  port: 8081

spring:
  profiles:
    active: local
  config:
    name: ucsal-tcc

---
spring:
  config:
    activate:
      on-profile: heroku
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  security:
    jwt:
      token:
        secret-key: ${JWT_SECRET_KEY}
        expire-length: 86400000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
debug: true


---

server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb
  security:
    jwt:
      token:
        secret-key: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*yL5S8EJN:%P:X%H9>#nYLrX}@s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
        expire-length: 86400000
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
      javax:
        persistence:
          query:
            timeout: '50'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

  h2:
    console:
      path: /h2
      enabled: true
      settings:
        trace: false
        web-allow-others: false

---

spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projeto_final
    username: postgres
    password: 300339
  security:
    jwt:
      token:
        secret-key: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*yL5S8EJN:%P:X%H9>#nYLrX}@s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
        expire-length: 86400000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true
