name: projetofinal_mobile
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  
  #Funcionalidades do Sistema
  flutter_modular: ^5.0.3
  logger: ^1.1.0
  meta: ^1.7.0

  # Requisições HTTP
  dio: ^4.0.6
  jwt_decode: ^0.3.1

  # Estilização
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  liquid_pull_to_refresh: ^3.0.1

  # Armazenamento
  shared_preferences: ^2.0.15

  # Componentes
  flutter_svg: ^1.1.4
  simple_animations: ^4.0.1
  code_text_field: ^1.0.2

  #Internacionalização
  intl_utils: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  modular_test: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
    # - images/

flutter_intl:
  enabled: true
  main_locale: pt

